### ISSUE TITLE
Ability to define where to run hugo

### ISSUE THREAD

**Issue by JamesStuddart** [1v0dev/hugo-intellij-plugin#1]
Due to the way I structure all my hugo apps I run my projects from the directory above the config.toml, I have all my hugo installation within a subfolder called 'src'

Having the ability to define a project directory to run hugo from, would be very useful.

**Comment by 1v0dev** [comment]
Thanks for the feedback. Are you running Hugo with source option to specify the dir:
`-s, --source string          filesystem path to read files relative from`
If so, you can specify it in the Arguments field in the run configuration. But I can add a separate field for the project directory too.
Just trying to figure out what the exact use case is. If you provide a sample of your app structure and what commands you use when building manually, it will be very helpful.

**Comment by JamesStuddart** [comment]
I wasn't aware of that command, I normally end up using npm's package.json to define the execution.

the command I run from npm is `cd ../src/  && hugo serve -D -v` as the package.json resides in another folder.

The stucture often looks like this

```
|- repo-folder
   |- src 
   |- static-src
   |- README.md
```

where src is the HUGO source and static src, is the npm tasks I run during the build process in more complex setups.

**Comment by 1v0dev** [comment]
Got it. Let me know if that `hugo -s path` works for you. If it does not, I will add the possibility to change the current context dir (like `cd`) where the `hugo` command is run.

**Comment by JamesStuddart** [comment]
I've tried running the plugin and I get the following error:

```
Error running 'Hugo':
Cannot run program "hugo" (in directory "D:\code\github\gwynddraig"): CreateProcess error=2, The system cannot find the file specified
```

**Comment by 1v0dev** [comment]
Thanks. I will debug and add the project dir option.

**Comment by 1v0dev** [comment]
Done. Now you can specify any dir as you Hugo project dir to run the commands there. The update is published, should be available soon

**Comment by JamesStuddart** [comment]
Awesome, thanks for moving quickly on this, I look forward to giving it a run, I'll close this this issue now.
