### ISSUE TITLE
Ability to specify document name

### ISSUE THREAD

**Issue by khayyamsaleem** [1v0dev/hugo-intellij-plugin#3]
Rather than specifying a full name, it should additionally allow simply specifying the document title, and then the code can handle auto-formatting it to conform to a filename with dashes in place of spaces and appending `.md`

**Comment by 1v0dev** [comment]
Implemented in version 0.4.0 (update submitted) - added new option in the settings to toggle auto formatting for hugo new. It will replace spaces with underscores and add .md if missing
