### ISSUE TITLE
Ability to create leaf bundles

### ISSUE THREAD

**Issue by khayyamsaleem** [1v0dev/hugo-intellij-plugin#4]
In newer versions of hugo, documents can be represented as **folders** instead of just files. This allows the documenter to include all resources the document requires (images, pdfs, other static assets) in the same folder as the document. The folder-name represents the document and all its assets, and each folder has an `index.md` file with the actual content.

Ideally, the plugin would support a checkbox in the `hugo new` dialog box that would allow the document to be created as a bundle, instead of just a single markdown file.

**Comment by 1v0dev** [comment]
Thanks for the suggestions. I would investigate this and your other issue and try to add the functionality.

**Comment by 1v0dev** [comment]
Implemented in version 0.4.0 (update submitted) - added a checkbox in Hugo New dialog "Create bundle". When toggled it will create a new folder with the specified name and add index.md file inside
