### ISSUE TITLE
Hugo not (yet) supported on IntelliJ 2021.3

### ISSUE THREAD

**Issue by opwvhk** [1v0dev/hugo-intellij-plugin#5]
The current Hugo plugin is valid for IntelliJ versions up to build `212.*`
In my experience (I'm author of a JetBrains plugin myself), increasing the `until-build` number to `213.*` is quite painless.

In case not, this page may list the reasons: https://plugins.jetbrains.com/docs/intellij/api-changes-list-2021.html

Request: please update `until-build` to `213.*`

**Comment by 1v0dev** [comment]
Update to support 2021.3 is pushed to JetBrains for review. Should be available soon. I usually try to add support for the latest version quickly, but it takes me a couple of days sometimes.
