### ISSUE TITLE
Update to support Rider 2023.3 (and other 2023.3 products)

### ISSUE THREAD

**Issue by somethingSTRANGE** [1v0dev/hugo-intellij-plugin#9]
The current 0.4.10 release is only usable in 2019.2 — 2023.2.5.

Please update version support so that the plugin can be used in 2023.3.* or 2023.3.1.

**Comment by 1v0dev** [comment]
I try to update as soon as new version is released but it is just a side probject so it takes me some time. Sorry for the delay. The new version with support for 2023.3 is submitted for review to JetBrains and should be available shortly.
